### ISSUE TITLE
My Confusion About Equation (11)

### ISSUE THREAD

**Issue by WuYunfan** [jimmy-academia/MSOPDS#1]
Dear authors,

I have read your paper with great interest. The Multilevel Stackelberg Optimization over Progressive Differentiable Surrogate (MSOPDS) method is innovative and insightful for addressing the Multiplayer Comprehensive Attack problem.

However, I have some confusion regarding Equation (11) in the paper. Based on my understanding of the chain rule, I believe the total derivative \( \frac{dL_p}{dX_p} \) should be expressed as:

\[ \frac{dL_p}{dX_p} = \frac{\partial L_p}{\partial X_p} + \frac{\partial L_p}{\partial X_q} \frac{\partial X_q}{\partial X_p} \]

In this context, the attacker's poisoning plan \( X_p \) influences its objective function \( L_p \) through two paths:

1. **Direct influence**, corresponding to the first partial derivative term \( \frac{\partial L_p}{\partial X_p} \).
2. **Indirect influence**, by affecting the opponent's poisoning plan \( X_q \), which in turn affects \( L_p \), corresponding to the product term \( \left( \frac{\partial L_p}{\partial X_q} \right) \left( \frac{\partial X_q}{\partial X_p} \right) \).

From this perspective, it seems that the terms should be added together, rather than subtracted. Therefore, I am wondering if the minus sign in Equation (11) might be a typo and should be changed to a plus sign:

\[ \frac{dL_p}{dX_p} = \frac{\partial L_p}{\partial X_p} + \frac{\partial L_p}{\partial X_q} \frac{\partial X_q}{\partial X_p} \]

I would greatly appreciate it if you could clarify this point. Thank you for your attention and for the excellent work presented in this paper.

Best regards

**Comment by jimmy-academia** [comment]
Yes, I think it is a typo. 
(Note that the method follows the subsequent expanded Eq 13)
