### ISSUE TITLE
Request for ciao.pkl, library.pkl, and epinion.pkl Files

### ISSUE THREAD

**Issue by Hanyuzhen0826** [jimmy-academia/MSOPDS#2]
Dear Team：

Thank you for sharing this amazing project! I noticed that the ciao.pkl, library.pkl, and epinions.pkl files are required for running the code. However, I was unable to locate these files in the repository.Could you please provide these packages or let me know if I can find them elsewhere? They appear to be essential for running the project.

Looking forward to your response. Thanks for your help!

Best regards,

**Comment by jimmy-academia** [comment]
The scripts
```
bash data/get_data.sh
bash data/prepare_data.sh
```
are used to prepare the dataset files, which should create the required files.

You may need to modify `data/get_data.sh` to include downloading the `librarything` dataset, which follows the `epinions` dataset, as they are both from the same source by [Professor Julian McAuley, UCSD](https://cseweb.ucsd.edu/~jmcauley/). Specifically, check this link: https://cseweb.ucsd.edu/~jmcauley/datasets.html#social_data

**Comment by Hanyuzhen0826** [comment]
Thank you so much for your prompt reply! I sincerely apologize for not
thoroughly reading the detailed instructions provided by the author
regarding the code execution process.

I truly appreciate your help and assistance in this matter. Wishing you
continued success in your research and good health.

Once again, thank you for your support!

Yeh Chin-Yuan ***@***.***> 于2024年12月6日周五 14:04写道：
